--2.1 SELECT
SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

--2.2 ORDER BY

SELECT * FROM ALBUM ORDER BY TITLE DESC ;

SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

--2.3 INSERT INTO

INSERT ALL
    INTO GENRE VALUES (27, 'Smooth Jazz')
    INTO GENRE VALUES (28, 'German Rock')
SELECT * FROM DUAL;

INSERT ALL
    INTO EMPLOYEE VALUES (9, 'Capulet', 'River','Online Sales', 2, TO_DATE('1980-04-18', 'yyyy-mm-dd'), TO_DATE('2019-03-15', 'yyyy-mm-dd'), 
    '123 Italian Boards', 'Denver', 'Colorodo', 'United States', '33042', '+1 334-323-2321', '+2 344-232-2323','capuletR@gmail.com')
    INTO EMPLOYEE VALUES (10,'Montegue', 'Rain', 'Floor Sales', 2, TO_DATE('1945-09-08', 'yyyy-mm-dd'), TO_DATE('2019-03-14', 'yyyy-mm-dd'),
    '33 Balcony Rose', 'East Kilbride', 'Scotland', 'United Kingdom', 'TSF 42RW', '+9 334-333-2321', '+9 344-554-2323','montagueR@gmail.com')
    INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, SUPPORTREPID) VALUES
        (60, 'Bob', 'Evans', 'macaroniCheese@gmail.com', 5)
    INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, SUPPORTREPID) VALUES 
        (61, 'Mary', 'Currie', 'radiation4me@gmail.com', 3)
SELECT * FROM DUAL;

--2.4 UPDATE

UPDATE 
    CUSTOMER
SET 
    FIRSTNAME = 'ROBERT',
    LASTNAME = 'WALTER'
WHERE 
    CUSTOMERID = 32;
    

UPDATE 
    ARTIST
SET 
    NAME = 'CCR'
WHERE 
    NAME = 'Creedence Clearwater Revival';

--2.5 LIKE

SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

--2.6 BETWEEN

SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;

SELECT * FROM 
    EMPLOYEE 
WHERE 
    HIREDATE 
BETWEEN 
    TO_DATE('2003-06-01', 'yyyy-mm-dd') 
    AND 
    TO_DATE('2004-03-01', 'yyyy-mm-dd');

--2.7 DELETE

DELETE FROM
    CUSTOMER
WHERE
    CUSTOMERID = 32;

DELETE FROM
    INVOICE
WHERE
    CUSTOMERID = 32;

DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 116;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 342;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 245;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 268;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 290;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 50;
    
DELETE FROM 
    INVOICELINE
WHERE
    INVOICEID = 61;
    
--3 SQL FUNCTIONS
--3.1 SYSTEMS DEFINED FUNCTIONS

SELECT CURRENT_TIMESTAMP
FROM DUAL;

CREATE FUNCTION MEDIATYPE_LENGTH
   [ (parameter [,parameter]) ]

   RETURN return_datatype

BEGIN
   executable_section

[EXCEPTION
   exception_section]

END [MEDIATYPE_LENGTH];




